
---
apiVersion: move2kube.konveyor.io/v1alpha1
kind: CfApps
metadata:
    name: cf-provider-name
spec:
    applications:
        - application:
            buildpack: https://github.com/cloudfoundry/java-buildpack
            command: ""
            createdat: "2021-12-14T10:01:40Z"
            detectedbuildpack: java
            detectedbuildpackguid: ""
            detectedstartcommand: 'JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR -XX:ActiveProcessorCount=$(nproc) -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE -totMemory=$MEMORY_LIMIT -loadedClasses=23199 -poolType=metaspace -stackThreads=250 -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && MALLOC_ARENA_MAX=2 SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/. org.springframework.boot.loader.JarLauncher'
            diego: true
            diskquota: 1024
            dockercredentials:
                password: ""
                username: ""
            dockercredentialsjson: {}
            dockerimage: ""
            enablessh: true
            environment: {}
            guid: id1
            healthcheckhttpendpoint: ""
            healthchecktimeout: 0
            healthchecktype: port
            instances: 1
            memory: 1024
            name: orders
            packagestate: STAGED
            packageupdatedat: "2021-12-14T10:01:49Z"
            ports:
                - 8080
            spacedata:
                entity:
                    allowssh: true
                    createdat: ""
                    guid: space-id
                    isolationsegmentguid: ""
                    name: dev
                    organizationguid: org-id
                    orgdata:
                        entity:
                            createdat: ""
                            defaultisolationsegmentguid: ""
                            guid: org-id
                            name: org-name
                            quotadefinitionguid: quota-def-id
                            status: active
                            updatedat: ""
                        meta:
                            createdat: "2020-10-05T05:29:31Z"
                            guid: org-id
                            updatedat: "2020-10-05T05:29:31Z"
                            url: /v2/organizations/org-id
                    orgurl: /v2/organizations/org-id
                    quotadefinitionguid: ""
                    updatedat: ""
                meta:
                    createdat: "2020-10-05T05:29:46Z"
                    guid: space-id
                    updatedat: "2020-10-05T05:29:46Z"
                    url: /v2/spaces/space-id
            spaceguid: space-id
            spaceurl: /v2/spaces/space-id
            stackguid: stack-id
            stagingfaileddescription: ""
            stagingfailedreason: ""
            state: STARTED
            updatedat: "2022-02-08T10:15:53Z"
          environment:
            applicationenv:
                VCAP_APPLICATION: '{"application_id":"id1","application_name":"orders","application_uris":["orders-proud-bilby-rf.net"],"application_version":"app-ver1","cf_api":"cf-api-url","limits":{"disk":1024,"fds":16384,"mem":1024},"name":"orders","organization_id":"org-id","organization_name":"org-name","process_id":"id1","process_type":"web","space_id":"space-id","space_name":"dev","uris":["orders-proud-bilby-rf.net"],"users":null,"version":"app-ver1"}'
            environment: {}
            runningenv:
                BLUEMIX_REGION: region
            stagingenv:
                BLUEMIX_REGION: region
            systemenv:
                VCAP_SERVICES: '{"cloud-object-storage":[{"binding_guid":"binding-id","binding_name":null,"credentials":{"apikey":"key","endpoints":"cloud-object-storage-endpoints","iam_apikey_description":"Auto-generated for binding","iam_apikey_name":"apikey-name","iam_role_crn":"serviceRole:Writer","iam_serviceid_crn":"serviceid:ServiceId","resource_instance_id":"resource-id"},"instance_guid":"instance-id","instance_name":"Cloud Object Storage-0h","label":"cloud-object-storage","name":"Cloud Object Storage-0h","plan":"Lite","provider":null,"syslog_drain_url":null,"tags":["Lite","storage"],"volume_mounts":[]}]}'
        - application:
            buildpack: https://github.com/cloudfoundry/java-buildpack
            command: ""
            createdat: "2021-12-14T10:04:00Z"
            detectedbuildpack: java
            detectedbuildpackguid: ""
            detectedstartcommand: 'JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR -XX:ActiveProcessorCount=$(nproc) -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE -totMemory=$MEMORY_LIMIT -loadedClasses=24458 -poolType=metaspace -stackThreads=250 -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && MALLOC_ARENA_MAX=2 SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/. org.springframework.boot.loader.JarLauncher'
            diego: true
            diskquota: 1024
            dockercredentials:
                password: ""
                username: ""
            dockercredentialsjson: {}
            dockerimage: ""
            enablessh: true
            environment: {}
            guid: id2
            healthcheckhttpendpoint: ""
            healthchecktimeout: 0
            healthchecktype: port
            instances: 1
            memory: 1024
            name: gateway
            packagestate: STAGED
            packageupdatedat: "2021-12-14T10:04:09Z"
            ports:
                - 8080
            spacedata:
                entity:
                    allowssh: true
                    createdat: ""
                    guid: space-id
                    isolationsegmentguid: ""
                    name: dev
                    organizationguid: org-id
                    orgdata:
                        entity:
                            createdat: ""
                            defaultisolationsegmentguid: ""
                            guid: org-id
                            name: org-name
                            quotadefinitionguid: quota-def-id
                            status: active
                            updatedat: ""
                        meta:
                            createdat: "2020-10-05T05:29:31Z"
                            guid: org-id
                            updatedat: "2020-10-05T05:29:31Z"
                            url: /v2/organizations/org-id
                    orgurl: /v2/organizations/org-id
                    quotadefinitionguid: ""
                    updatedat: ""
                meta:
                    createdat: "2020-10-05T05:29:46Z"
                    guid: space-id
                    updatedat: "2020-10-05T05:29:46Z"
                    url: /v2/spaces/space-id
            spaceguid: space-id
            spaceurl: /v2/spaces/space-id
            stackguid: stack-id
            stagingfaileddescription: ""
            stagingfailedreason: ""
            state: STARTED
            updatedat: "2021-12-14T10:05:43Z"
          environment:
            applicationenv:
                VCAP_APPLICATION: '{"application_id":"id2","application_name":"gateway","application_uris":["gateway-restless-fossa-ws.net"],"application_version":"app-ver2","cf_api":"cf-api-url","limits":{"disk":1024,"fds":16384,"mem":1024},"name":"gateway","organization_id":"org-id","organization_name":"org-name","process_id":"id2","process_type":"web","space_id":"space-id","space_name":"dev","uris":["gateway-restless-fossa-ws.net"],"users":null,"version":"app-ver2"}'
            environment: {}
            runningenv:
                BLUEMIX_REGION: region
            stagingenv:
                BLUEMIX_REGION: region
            systemenv:
                VCAP_SERVICES: '{}'
        - application:
            buildpack: https://github.com/cloudfoundry/nodejs-buildpack
            command: npm run start
            createdat: "2021-12-14T14:54:25Z"
            detectedbuildpack: nodejs
            detectedbuildpackguid: ""
            detectedstartcommand: npm start
            diego: true
            diskquota: 1024
            dockercredentials:
                password: ""
                username: ""
            dockercredentialsjson: {}
            dockerimage: ""
            enablessh: true
            environment: {}
            guid: id3
            healthcheckhttpendpoint: ""
            healthchecktimeout: 0
            healthchecktype: port
            instances: 1
            memory: 1024
            name: frontend
            packagestate: STAGED
            packageupdatedat: "2021-12-14T14:59:40Z"
            ports:
                - 8080
            spacedata:
                entity:
                    allowssh: true
                    createdat: ""
                    guid: space-id
                    isolationsegmentguid: ""
                    name: dev
                    organizationguid: org-id
                    orgdata:
                        entity:
                            createdat: ""
                            defaultisolationsegmentguid: ""
                            guid: org-id
                            name: org-name
                            quotadefinitionguid: quota-def-id
                            status: active
                            updatedat: ""
                        meta:
                            createdat: "2020-10-05T05:29:31Z"
                            guid: org-id
                            updatedat: "2020-10-05T05:29:31Z"
                            url: /v2/organizations/org-id
                    orgurl: /v2/organizations/org-id
                    quotadefinitionguid: ""
                    updatedat: ""
                meta:
                    createdat: "2020-10-05T05:29:46Z"
                    guid: space-id
                    updatedat: "2020-10-05T05:29:46Z"
                    url: /v2/spaces/space-id
            spaceguid: space-id
            spaceurl: /v2/spaces/space-id
            stackguid: stack-id
            stagingfaileddescription: ""
            stagingfailedreason: ""
            state: STARTED
            updatedat: "2021-12-14T15:15:38Z"
          environment:
            applicationenv:
                VCAP_APPLICATION: '{"application_id":"id3","application_name":"frontend","application_uris":["frontend-patient-oryx.net"],"application_version":"app-ver3","cf_api":"cf-api-url","limits":{"disk":1024,"fds":16384,"mem":1024},"name":"frontend","organization_id":"org-id","organization_name":"org-name","process_id":"id3","process_type":"web","space_id":"space-id","space_name":"dev","uris":["frontend-patient-oryx.net"],"users":null,"version":"app-ver3"}'
            environment: {}
            runningenv:
                BLUEMIX_REGION: region
            stagingenv:
                BLUEMIX_REGION: region
            systemenv:
                VCAP_SERVICES: '{}'

...
