apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: myproject-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: inventory
      name: inventory
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: index.docker.io/korificf/inventory:latest
              imagePullPolicy: Always
              name: inventory
              ports:
                - containerPort: 8080
              resources:
                requests:
                  ephemeral-storage: "0"
                  memory: "0"
          imagePullSecrets:
            - name: index-docker-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: orders
      name: orders
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - env:
                - name: VCAP_APPLICATION
                  valueFrom:
                    secretKeyRef:
                      key: VCAP_APPLICATION
                      name: orders-vcapasenv
                - name: CLOUD_OBJECT_STORAGE_0H_IAM_ROLE_CRN
                  valueFrom:
                    secretKeyRef:
                      key: CLOUD_OBJECT_STORAGE_0H_IAM_ROLE_CRN
                      name: orders-vcapasenv
                - name: CLOUD_OBJECT_STORAGE_0H_IAM_SERVICEID_CRN
                  valueFrom:
                    secretKeyRef:
                      key: CLOUD_OBJECT_STORAGE_0H_IAM_SERVICEID_CRN
                      name: orders-vcapasenv
                - name: CLOUD_OBJECT_STORAGE_0H_ENDPOINTS
                  valueFrom:
                    secretKeyRef:
                      key: CLOUD_OBJECT_STORAGE_0H_ENDPOINTS
                      name: orders-vcapasenv
                - name: CLOUD_OBJECT_STORAGE_0H_IAM_APIKEY_DESCRIPTION
                  valueFrom:
                    secretKeyRef:
                      key: CLOUD_OBJECT_STORAGE_0H_IAM_APIKEY_DESCRIPTION
                      name: orders-vcapasenv
                - name: VCAP_SERVICES
                  valueFrom:
                    secretKeyRef:
                      key: VCAP_SERVICES
                      name: orders-vcapasenv
                - name: BLUEMIX_REGION
                  value: region
                - name: CLOUD_OBJECT_STORAGE_0H_RESOURCE_INSTANCE_ID
                  valueFrom:
                    secretKeyRef:
                      key: CLOUD_OBJECT_STORAGE_0H_RESOURCE_INSTANCE_ID
                      name: orders-vcapasenv
                - name: CLOUD_OBJECT_STORAGE_0H_APIKEY
                  valueFrom:
                    secretKeyRef:
                      key: CLOUD_OBJECT_STORAGE_0H_APIKEY
                      name: orders-vcapasenv
                - name: CLOUD_OBJECT_STORAGE_0H_IAM_APIKEY_NAME
                  valueFrom:
                    secretKeyRef:
                      key: CLOUD_OBJECT_STORAGE_0H_IAM_APIKEY_NAME
                      name: orders-vcapasenv
                - name: SPRING_CONFIG_IMPORT
                  value: /vcap/vcap-properties.yaml
              image: index.docker.io/korificf/orders:latest
              imagePullPolicy: Always
              name: orders
              ports:
                - containerPort: 8080
              resources:
                requests:
                  ephemeral-storage: 1024M
                  memory: 1024M
              volumeMounts:
                - mountPath: /vcap
                  name: vcapsecretvolume
          imagePullSecrets:
            - name: index-docker-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
          volumes:
            - name: vcapsecretvolume
              secret:
                secretName: orders-vcapasspringbootproperties
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: customers
      name: customers
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: index.docker.io/korificf/customers:latest
              imagePullPolicy: Always
              name: customers
              ports:
                - containerPort: 8080
              resources:
                requests:
                  ephemeral-storage: "0"
                  memory: "0"
          imagePullSecrets:
            - name: index-docker-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: frontend
      name: frontend
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - env:
                - name: BLUEMIX_REGION
                  value: region
                - name: VCAP_SERVICES
                  valueFrom:
                    secretKeyRef:
                      key: VCAP_SERVICES
                      name: frontend-vcapasenv
                - name: VCAP_APPLICATION
                  valueFrom:
                    secretKeyRef:
                      key: VCAP_APPLICATION
                      name: frontend-vcapasenv
              image: index.docker.io/korificf/frontend:latest
              imagePullPolicy: Always
              name: frontend
              ports:
                - containerPort: 8080
              resources:
                requests:
                  ephemeral-storage: 1024M
                  memory: 1024M
          imagePullSecrets:
            - name: index-docker-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: gateway
      name: gateway
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - env:
                - name: JBP_CONFIG_SPRING_AUTO_RECONFIGURATION
                  value: '{ enabled: false }'
                - name: SPRING_PROFILES_ACTIVE
                  value: dev
                - name: BLUEMIX_REGION
                  value: region
                - name: VCAP_SERVICES
                  valueFrom:
                    secretKeyRef:
                      key: VCAP_SERVICES
                      name: gateway-vcapasenv
                - name: VCAP_APPLICATION
                  valueFrom:
                    secretKeyRef:
                      key: VCAP_APPLICATION
                      name: gateway-vcapasenv
                - name: SPRING_CONFIG_IMPORT
                  value: /vcap/vcap-properties.yaml
              image: index.docker.io/korificf/gateway:latest
              imagePullPolicy: Always
              name: gateway
              ports:
                - containerPort: 8080
              resources:
                requests:
                  ephemeral-storage: 1024M
                  memory: 1024M
              volumeMounts:
                - mountPath: /vcap
                  name: vcapsecretvolume
          imagePullSecrets:
            - name: index-docker-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
          volumes:
            - name: vcapsecretvolume
              secret:
                secretName: gateway-vcapasspringbootproperties
    status: {}
parameters: []
