
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        move2kube.konveyor.io/service.expose: "false"
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: database
    name: database
spec:
    replicas: {{ index .Values "common" "replicas" }}
    selector:
        matchLabels:
            move2kube.konveyor.io/service: database
    strategy: {}
    template:
        metadata:
            annotations:
                move2kube.konveyor.io/service.expose: "false"
            creationTimestamp: null
            labels:
                move2kube.konveyor.io/service: database
            name: database
        spec:
            containers:
                - env:
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            key: password
                            name: database-secret
                    - name: PGDATA
                      value: /var/lib/postgresql/data/pgdata
                  image: postgres:14.5
                  imagePullPolicy: Always
                  name: database
                  ports:
                    - containerPort: 5432
                      protocol: TCP
                  resources: {}
                  volumeMounts:
                    - mountPath: /docker-entrypoint-initdb.d
                      name: secret-volume
                      readOnly: true
            restartPolicy: Always
            securityContext: {}
            volumes:
                - name: secret-volume
                  secret:
                    secretName: database-secret
status: {}

...
