
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: gateway
    name: gateway
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - env:
                    - name: JBP_CONFIG_SPRING_AUTO_RECONFIGURATION
                      value: '{ enabled: false }'
                    - name: SPRING_PROFILES_ACTIVE
                      value: dev
                    - name: BLUEMIX_REGION
                      value: region
                    - name: VCAP_SERVICES
                      valueFrom:
                        secretKeyRef:
                            key: VCAP_SERVICES
                            name: gateway-vcapasenv
                    - name: VCAP_APPLICATION
                      valueFrom:
                        secretKeyRef:
                            key: VCAP_APPLICATION
                            name: gateway-vcapasenv
                    - name: SPRING_CONFIG_IMPORT
                      value: /vcap/vcap-properties.yaml
                  image: index.docker.io/korificf/gateway:latest
                  imagePullPolicy: Always
                  name: gateway
                  ports:
                    - containerPort: 8080
                  resources:
                    requests:
                        ephemeral-storage: 1024M
                        memory: 1024M
                  volumeMounts:
                    - mountPath: /vcap
                      name: vcapsecretvolume
            imagePullSecrets:
                - name: index-docker-io-imagepullsecret
            restartPolicy: Always
            securityContext: {}
            volumes:
                - name: vcapsecretvolume
                  secret:
                    secretName: gateway-vcapasspringbootproperties
status: {}

...
